### PR TITLE
add inner_cover for BACHELORs

### PR DESCRIPTION
**Pull request by xplorld**
SJTU authority now requires a new cover for bachelor's thesis. Instead of drawing one by tex itself, now we have to use a `doc` file provided by SJTU.
added support for this. now work pipeline:

1. download the inner_cover file from SJTU
2. change it and make the pdf
3. put the pdf to `pdf/inner_cover.pdf`
4. select `\documentclass[bachelor,...]` in `thesis.pdf`.

effect:
removed hand-written chinese and english cover, instead inserted the pdf cover at the beginning.

preview: 
image

### CODE REVIEW

**Comment by xplorld** [comment]
alert: not tested on `dev` branch, but happened to have no conflicts.

**Comment by gaocegege** [comment]
It will work in `dev`, IMO. and thanks you for the awesome cover. LGTM

But it will be better if we could implement the cover in LaTeX. 🤔

**Comment by xplorld** [comment]
I don't know... IMHO since the school requires *this* `doc`, we should use this `doc`.

**Comment by gaocegege** [comment]
But the pdf is not editable, then I think it will not help the users to make things easy :thinking:

**Comment by gaocegege** [comment]
Hi, ruiyang

现在我们已经合并了本科生标题页的实现 #242 , 所以我先关闭这个问题了. 如果你有新的问题或者觉得现在的实现还有问题可以提新的 PR :smiley: 谢谢你的贡献

祝好

**Pull request closed without merging**
