### PR TITLE
A new cover solution for thesis of bachelor with vector logos

### PR DESCRIPTION
**Pull request by AlexaraWu**
thesis

Draw cover for bachelor's thesis with vector logo graphs. Only works with option `bachelor`.

### CODE REVIEW

**Comment by gaocegege** [comment]
Thanks for your contribution.

It is dup with #200 , IMO 🤔

**Comment by AlexaraWu** [comment]
@gaocegege Same feature, but not dup.
Not only looks better, but also works only with the option `bachelor`. More compatible with the entire project.

**Comment by gaocegege** [comment]
re @AlexaraWu Awesome, I will take a look 🎉

**Comment by gaocegege** [comment]
@AlexaraWu Hi, 这个 PR 是为什么 close 了? 是有什么问题么

**Comment by AlexaraWu** [comment]
@gaocegege 我在 [上海交通大学视觉形象识别系统](http://vi.sjtu.edu.cn/) 发现了新的矢量图标文件，样式原来的略有不同；再者这个 PR 第一次提交是用的是 EPS 文件，体积有点大。我计划用新图标另作一个干净的 PR。

**Comment by gaocegege** [comment]
SGTM

**Pull request closed without merging**
