### PR TITLE
Add an example resume

### PR DESCRIPTION
**Pull request by liweitianux**
Fix the `resumelist` environment in the meantime.

### CODE REVIEW

**Comment by liweitianux** [comment]
Fix #130 .

**Comment by gaocegege** [comment]
Thanks for your contribution! Could you please show us the snapshot of the resume?

**Comment by liweitianux** [comment]
@gaocegege Thanks.

Here is the picture of the generated resume page.
resume

Cheers

**Comment by gaocegege** [comment]
LGTM, we could add it. If there is any suggestion or issue about the resume we can fix in the incoming issues/PRs.

I will merge it after CI passed.

**Pull request merged**
