### PR TITLE
Fix keywords font size & Set PDF metadata (author, title, subject, keywords)

### PR DESCRIPTION
**Pull request by liweitianux**
Hello,

This pull request contains the following 3 commits:

1. Fix the font size of keywords
2. Merge keywords printing into the abstract environment
3. Auto set PDF metadata (author, title, subject, keywords)

Please review and merge. Thanks.

Cheers

### CODE REVIEW

**Comment by gaocegege** [comment]
Could you please explain more about the benefit of `Merge keywords printing into the abstract environment`?

**Comment by liweitianux** [comment]
@gaocegege 

I have put a brief explanation in the separate commit message, i.e.,

> The behaviors of the original `\keywords` and `\englishkeywords` commands
> are changed to define the corresponding variables, which will be used in
> PDF metadata by the following commit.

Since we'll need a variable where the keywords store for `hypersetup`, I choose to change the `\keywords` command to define that variable `sjtu@value@keywords`, which can also be used in the `abstract` environment, therefore the merge.

The mean reason for such a merge is to allow the definition of a variable `sjtu@value@keywords` needed by `hypersetup`.

Cheers

**Comment by gaocegege** [comment]
SGTM.

Thanks for your contribution!

**Comment by gaocegege** [comment]
BTW, I love your detailed commit message :clinking_glasses:

**Comment by liweitianux** [comment]
@gaocegege Thanks for reviewing and merging this PR.

BTW, what do the *SGTM* and *LGTM* mean? :grin:

**Comment by gaocegege** [comment]
Ref https://farer.org/2017/03/01/code-review-acronyms/

<div class="kg-card-markdown"><p>就像你可能不知道 <strong>现充</strong> 其实是 <strong>现实生活很充实的人生赢家</strong> 的缩写一样，我们经常看到 Github 上的码农们在 code review 时，把乱七八糟的缩写写得到处都是——娴熟的司机们都会使用缩写来达到提高逼格的效果——我们第一次看到时还是会出现一脸懵逼的状况，这里整理一下这些缩写都是什么含义，以后我们也可以欢快地装逼了。</p>
<ul>
<li><strong>PR:</strong> Pull Request. 拉取请求，给其他项目提交代码</li>
<li><strong>LGTM:</strong> Looks Good To Me. <s>朕知道了</s> 代码已经过 review，可以合并</li>
<li><strong>SGTM:</strong> Sounds Good To Me. 和上面那句意思差不多，也是已经通过了 review 的意思</li>
<li><strong>WIP:</strong> Work In Progress. 传说中提 PR 的最佳实践是，如果你有个改动很大的 PR，可以在写了一部分的情况下先提交，但是在标题里写上 WIP，以告诉项目维护者这个功能还未完成，方便维护者提前 review 部分提交的代码。</li>
<li><strong>PTAL:</strong> Please Take A Look. 你来瞅瞅？用来提示别人来看一下</li>
<li><strong>TBR:</strong> To Be Reviewed. 提示维护者进行 review</li>
<li><strong>TL;DR:</strong> Too Long; Didn't Read. 太长懒得看。也有很多文档在做简略描述之前会写这么一句</li>
<li><strong>TBD:</strong> To Be Done(or Defined/Discussed/Decided/Determined). 根据语境不同意义有所区别，但一般都是还没搞定的意思</li>
</ul>
<p>嗯，感觉特别中二。目前为止只见过这些，欢迎补充 =。=</p>
</div>

**Pull request merged**
