### PR TITLE
Fix English bachelor thesis

### PR DESCRIPTION
**Pull request by cxy1997**
Remove End English Abstract from English bachelor thesis

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]

**Comment by AlexaraWu** [comment]
`thesis.tex` is a just a sample, not the core code. I think it is unnecessary to apply this change.

**Comment by gaocegege** [comment]
It may be used by some users. If users do not use `thesis.tex`, it will not cause any additional error with the change. I think we could merge it since it has no side effect, at least.

**Comment by gaocegege** [comment]
WDYT @AlexaraWu

**Comment by AlexaraWu** [comment]
Well, it's up to you. @gaocegege

**Comment by gaocegege** [comment]
@cxy1997 
Thanks for your contribution!

**Pull request merged**
