### PR TITLE
add English README

### PR DESCRIPTION
**Pull request by scozv**
see weijianwen/SJTUThesis/#139

### CODE REVIEW

**Comment by weijianwen** [comment]
Thank you for your PR. Could you rebase (compact) the four commits into one? That would be easier for me to apply it to other branches on SJTUThesis.

**Comment by scozv** [comment]
hi, only one commit now.

**Comment by weijianwen** [comment]
This PR has been merged in 9e41de8. The dev branch will be merged into master in next release, which is expected in mid May.

**Comment by weijianwen** [comment]
My fault. I should have asked you to send a RP to the dev branch. In that case, the PR will be marked as _merged_ after I manually do a fast-forward merge.

Since the commit has been added to the repo. I'll close the RP. Thank you again for your contribution.

**Pull request closed without merging**
