### PR TITLE
add style option header-include-major

### PR DESCRIPTION
**Pull request by ShaolinFu**
to support the SEIEE template for Master of Engineering Management, which requires the major is included in header. 上海交通大学工程管理硕士学位论文

### CODE REVIEW

**Comment by skyzh** [comment]
That's cool! But PRs should go to SJTUTeX repository. I'll help merge this PR to the correct place.

Also, do you have any sample (or requirement of style) for master of engineering thesis? Apart from the information on cover page, does the SJTUThesis project satisfy all the style requirements for your thesis?

**Comment by ShaolinFu** [comment]
> That's cool! But PRs should go to SJTUTeX repository. I'll help merge this PR to the correct place.
> 
> Also, do you have any sample (or requirement of style) for master of engineering thesis? Apart from the information on cover page, does the SJTUThesis project satisfy all the style requirements for your thesis?

I'll sent you the sample doc via email.

**Comment by ShaolinFu** [comment]
I didn't check the style one by one, and I will let you know if the style is different.

**Comment by ShaolinFu** [comment]
@skyzh I didn't realized that commit to my master will cause the pull request updated. The new commit will affect the original statement, which is something you might not want to merge with master.

**Comment by skyzh** [comment]
No problem, I'll handle the rest for you next week :)

**Pull request closed without merging**
