### PR TITLE
添加 Travis CI 支持

### PR DESCRIPTION
**Pull request by AlexaraWu**
**Description:**

使用 Travis CI 进行持续集成，测试代码。

### CODE REVIEW

**Comment by gaocegege** [comment]
@htfy96 Could you enable this repository in Travis CI to test the PR?

**Comment by htfy96** [comment]
@gaocegege done
https://travis-ci.org/sjtug/SJTUThesis

**Comment by gaocegege** [comment]
@AlexaraWu Could you re-push the commit to trigger Travis CI build?

**Comment by AlexaraWu** [comment]
@gaocegege Done.

**Review by gaocegege — APPROVED** [review]
LGTM

**Pull request merged**
